/**
 * 导入/导出服务
 * 支持 Markdown、CSV、JSON 格式
 */

/**
 * 导出为 Markdown 格式（按标签分类）
 * @param {Array} stars - Stars 数据数组
 * @param {Object} metadata - 元数据对象（标签、笔记、摘要等）
 * @returns {string} Markdown 文本
 */
export function exportToMarkdown(stars, metadata) {
  let markdown = `# My GitHub Stars Collection\n\n`;
  markdown += `> 导出时间: ${new Date().toLocaleString("zh-CN")}\n`;
  markdown += `> 项目总数: ${stars.length}\n\n`;
  markdown += `---\n\n`;

  // 按标签分组
  const tagGroups = {};
  const untagged = [];

  stars.forEach((star) => {
    const repoMeta = metadata[star.id] || {};
    const tags = repoMeta.tags || [];

    if (tags.length === 0) {
      untagged.push(star);
    } else {
      tags.forEach((tag) => {
        if (!tagGroups[tag]) {
          tagGroups[tag] = [];
        }
        tagGroups[tag].push(star);
      });
    }
  });

  // 输出有标签的项目
  const sortedTags = Object.keys(tagGroups).sort();

  sortedTags.forEach((tag) => {
    markdown += `## 🏷️ ${tag}\n\n`;

    tagGroups[tag].forEach((star) => {
      const repoMeta = metadata[star.id] || {};
      markdown += `### [${star.name}](${star.htmlUrl})\n\n`;
      markdown += `**Owner:** [@${star.owner.login}](${star.owner.htmlUrl})\n\n`;

      if (star.description) {
        markdown += `**描述:** ${star.description}\n\n`;
      }

      // AI 摘要
      if (repoMeta.aiSummary?.summary) {
        markdown += `**AI 摘要:** ${repoMeta.aiSummary.summary}\n\n`;

        if (repoMeta.aiSummary.features?.length > 0) {
          markdown += `**主要功能:**\n`;
          repoMeta.aiSummary.features.forEach((feature) => {
            markdown += `- ${feature}\n`;
          });
          markdown += `\n`;
        }
      }

      // 笔记
      if (repoMeta.notes) {
        markdown += `**笔记:**\n${repoMeta.notes}\n\n`;
      }

      // 统计信息
      markdown += `**统计:** ⭐ ${star.stargazersCount.toLocaleString()} | 🔀 ${star.forksCount.toLocaleString()}`;

      if (star.language) {
        markdown += ` | 💻 ${star.language}`;
      }

      markdown += `\n\n`;
      markdown += `**更新于:** ${new Date(star.updatedAt).toLocaleDateString("zh-CN")}\n\n`;
      markdown += `---\n\n`;
    });
  });

  // 输出未分类的项目
  if (untagged.length > 0) {
    markdown += `## 📦 未分类\n\n`;

    untagged.forEach((star) => {
      const repoMeta = metadata[star.id] || {};
      markdown += `### [${star.name}](${star.htmlUrl})\n\n`;
      markdown += `**Owner:** [@${star.owner.login}](${star.owner.htmlUrl})\n\n`;

      if (star.description) {
        markdown += `**描述:** ${star.description}\n\n`;
      }

      if (repoMeta.aiSummary?.summary) {
        markdown += `**AI 摘要:** ${repoMeta.aiSummary.summary}\n\n`;
      }

      markdown += `**统计:** ⭐ ${star.stargazersCount.toLocaleString()} | 🔀 ${star.forksCount.toLocaleString()}`;

      if (star.language) {
        markdown += ` | 💻 ${star.language}`;
      }

      markdown += `\n\n`;
      markdown += `---\n\n`;
    });
  }

  markdown += `\n---\n\n`;
  markdown += `📅 Generated by [StarKeeper](https://github.com/Naloam/StarKeeper) on ${new Date().toLocaleDateString("zh-CN")}\n`;

  return markdown;
}

/**
 * 导出为 CSV 格式
 * @param {Array} stars - Stars 数据数组
 * @param {Object} metadata - 元数据对象
 * @returns {string} CSV 文本
 */
export function exportToCSV(stars, metadata) {
  // CSV 头部
  let csv =
    "Name,Full Name,Owner,Description,URL,Language,Stars,Forks,Updated,Tags,Notes,AI Summary\n";

  stars.forEach((star) => {
    const repoMeta = metadata[star.id] || {};
    const tags = (repoMeta.tags || []).join("; ");
    const notes = (repoMeta.notes || "").replace(/"/g, '""').replace(/\n/g, " ");
    const aiSummary = (repoMeta.aiSummary?.summary || "").replace(/"/g, '""');
    const description = (star.description || "").replace(/"/g, '""');

    csv += `"${star.name}",`;
    csv += `"${star.fullName}",`;
    csv += `"${star.owner.login}",`;
    csv += `"${description}",`;
    csv += `"${star.htmlUrl}",`;
    csv += `"${star.language || ""}",`;
    csv += `${star.stargazersCount},`;
    csv += `${star.forksCount},`;
    csv += `"${new Date(star.updatedAt).toISOString()}",`;
    csv += `"${tags}",`;
    csv += `"${notes}",`;
    csv += `"${aiSummary}"\n`;
  });

  return csv;
}

/**
 * 导出为 JSON 格式（完整数据）
 * @param {Array} stars - Stars 数据数组
 * @param {Object} metadata - 元数据对象
 * @returns {string} JSON 文本
 */
export function exportToJSON(stars, metadata) {
  const exportData = {
    version: "1.0.0",
    exportedAt: new Date().toISOString(),
    totalCount: stars.length,
    repositories: stars.map((star) => {
      const repoMeta = metadata[star.id] || {};

      return {
        id: star.id,
        name: star.name,
        fullName: star.fullName,
        owner: {
          login: star.owner.login,
          avatar: star.owner.avatarUrl,
          url: star.owner.htmlUrl,
        },
        description: star.description,
        url: star.htmlUrl,
        homepage: star.homepage,
        language: star.language,
        stars: star.stargazersCount,
        forks: star.forksCount,
        watchers: star.watchersCount,
        openIssues: star.openIssuesCount,
        createdAt: star.createdAt,
        updatedAt: star.updatedAt,
        pushedAt: star.pushedAt,
        topics: star.topics || [],
        // 用户元数据
        metadata: {
          tags: repoMeta.tags || [],
          notes: repoMeta.notes || "",
          color: repoMeta.color || "#3B82F6",
          aiSummary: repoMeta.aiSummary || null,
        },
      };
    }),
  };

  return JSON.stringify(exportData, null, 2);
}

/**
 * 触发文件下载
 * @param {string} content - 文件内容
 * @param {string} filename - 文件名
 * @param {string} mimeType - MIME 类型
 */
export function downloadFile(content, filename, mimeType = "text/plain") {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * 导出为 Markdown 并下载
 */
export function exportAndDownloadMarkdown(stars, metadata) {
  const markdown = exportToMarkdown(stars, metadata);
  const filename = `github-stars-${new Date().toISOString().split("T")[0]}.md`;
  downloadFile(markdown, filename, "text/markdown");
}

/**
 * 导出为 CSV 并下载
 */
export function exportAndDownloadCSV(stars, metadata) {
  const csv = exportToCSV(stars, metadata);
  const filename = `github-stars-${new Date().toISOString().split("T")[0]}.csv`;
  downloadFile(csv, filename, "text/csv");
}

/**
 * 导出为 JSON 并下载
 */
export function exportAndDownloadJSON(stars, metadata) {
  const json = exportToJSON(stars, metadata);
  const filename = `github-stars-${new Date().toISOString().split("T")[0]}.json`;
  downloadFile(json, filename, "application/json");
}

/**
 * 获取导出统计信息
 */
export function getExportStats(stars, metadata) {
  const taggedCount = stars.filter((star) => {
    const repoMeta = metadata[star.id] || {};
    return (repoMeta.tags || []).length > 0;
  }).length;

  const withNotesCount = stars.filter((star) => {
    const repoMeta = metadata[star.id] || {};
    return repoMeta.notes && repoMeta.notes.trim().length > 0;
  }).length;

  const withAISummaryCount = stars.filter((star) => {
    const repoMeta = metadata[star.id] || {};
    return repoMeta.aiSummary && repoMeta.aiSummary.summary;
  }).length;

  const allTags = new Set();
  stars.forEach((star) => {
    const repoMeta = metadata[star.id] || {};
    (repoMeta.tags || []).forEach((tag) => allTags.add(tag));
  });

  return {
    total: stars.length,
    tagged: taggedCount,
    untagged: stars.length - taggedCount,
    withNotes: withNotesCount,
    withAISummary: withAISummaryCount,
    totalTags: allTags.size,
  };
}

/**
 * 导出统计报告为 Markdown
 * @param {Object} statsData - 统计数据
 * @param {Array} stars - Stars 数据
 * @param {Object} metadata - 元数据
 * @returns {string} Markdown 格式的统计报告
 */
export function exportStatsReport(statsData, stars, metadata) {
  const { basic = {}, health, languages = [], tags = [], growth } = statsData || {};

  let markdown = `# StarKeeper 统计报告\n\n`;
  markdown += `> 生成时间: ${new Date().toLocaleString("zh-CN")}\n`;
  markdown += `> 报告版本: v1.0\n\n`;
  markdown += `---\n\n`;

  // 基础统计
  markdown += `## 📊 基础统计\n\n`;
  markdown += `| 指标 | 数值 | 占比 |\n`;
  markdown += `|------|------|------|\n`;
  markdown += `| 总 Stars 数 | ${basic.totalStars ?? 0} | 100% |\n`;
  markdown += `| 标签数 | ${basic.totalTags ?? 0} | - |\n`;
  markdown += `| 有笔记 | ${basic.withNotes ?? 0} | ${basic.notesPercentage ?? 0}% |\n`;
  markdown += `| 有 AI 摘要 | ${basic.withAISummary ?? 0} | ${basic.aiSummaryPercentage ?? 0}% |\n\n`;

  // 健康度分析
  const totalStars = basic.totalStars || 1; // 避免除零
  if (health && health.analyzedCount > 0) {
    markdown += `## 🏥 健康度分析\n\n`;
    markdown += `**平均健康度:** ${health.averageScore} 分\n\n`;
    markdown += `**已分析项目:** ${health.analyzedCount} / ${totalStars} (${health.analyzedPercentage}%)\n\n`;
    markdown += `| 等级 | 数量 | 占比 |\n`;
    markdown += `|------|------|------|\n`;
    markdown += `| 优秀 (80-100) | ${health.distribution?.excellent || 0} | ${(((health.distribution?.excellent || 0) / totalStars) * 100).toFixed(1)}% |\n`;
    markdown += `| 良好 (60-79) | ${health.distribution?.good || 0} | ${(((health.distribution?.good || 0) / totalStars) * 100).toFixed(1)}% |\n`;
    markdown += `| 一般 (40-59) | ${health.distribution?.fair || 0} | ${(((health.distribution?.fair || 0) / totalStars) * 100).toFixed(1)}% |\n`;
    markdown += `| 较差 (20-39) | ${health.distribution?.poor || 0} | ${(((health.distribution?.poor || 0) / totalStars) * 100).toFixed(1)}% |\n`;
    markdown += `| 严重 (0-19) | ${health.distribution?.critical || 0} | ${(((health.distribution?.critical || 0) / totalStars) * 100).toFixed(1)}% |\n`;
    markdown += `| 未分析 | ${health.distribution?.unknown || 0} | ${(((health.distribution?.unknown || 0) / totalStars) * 100).toFixed(1)}% |\n\n`;
  }

  // 语言分布
  if (languages && languages.length > 0) {
    markdown += `## 💻 编程语言分布 (Top 10)\n\n`;
    markdown += `| 排名 | 语言 | 项目数 | 占比 |\n`;
    markdown += `|------|------|--------|------|\n`;
    languages.slice(0, 10).forEach((lang, index) => {
      markdown += `| ${index + 1} | ${lang.language} | ${lang.count} | ${lang.percentage}% |\n`;
    });
    markdown += `\n`;
  }

  // 标签统计
  if (tags && tags.length > 0) {
    markdown += `## 🏷️ 热门标签 (Top 15)\n\n`;
    markdown += `| 排名 | 标签 | 使用次数 | 占比 |\n`;
    markdown += `|------|------|----------|------|\n`;
    tags.slice(0, 15).forEach((tag, index) => {
      markdown += `| ${index + 1} | ${tag.tag} | ${tag.count} | ${tag.percentage}% |\n`;
    });
    markdown += `\n`;
  }

  // Stars 增长趋势
  if (growth && growth.length > 0) {
    markdown += `## 📈 Stars 增长趋势\n\n`;
    markdown += `**总时间跨度:** ${growth[0].month} ~ ${growth[growth.length - 1].month}\n\n`;

    // 最近6个月
    const recent6Months = growth.slice(-6);
    markdown += `### 最近 6 个月趋势\n\n`;
    markdown += `| 月份 | 新增 | 累计 |\n`;
    markdown += `|------|------|------|\n`;
    recent6Months.forEach((item) => {
      markdown += `| ${item.month} | ${item.count} | ${item.cumulative} |\n`;
    });
    markdown += `\n`;

    // 增长率分析
    if (growth.length >= 2) {
      const latestMonth = growth[growth.length - 1];
      const previousMonth = growth[growth.length - 2];
      const monthlyGrowth = latestMonth.count;
      const growthRate =
        previousMonth.count > 0
          ? (((latestMonth.count - previousMonth.count) / previousMonth.count) * 100).toFixed(1)
          : "N/A";

      markdown += `**上月新增:** ${monthlyGrowth} 个项目\n`;
      markdown += `**环比增长:** ${growthRate}%\n\n`;
    }
  }

  // 活跃度分析
  const recentlyActive = stars
    .filter((star) => star.pushedAt)
    .sort((a, b) => new Date(b.pushedAt) - new Date(a.pushedAt))
    .slice(0, 10);

  if (recentlyActive.length > 0) {
    markdown += `## 🔥 最近活跃项目 (Top 10)\n\n`;
    markdown += `| 项目 | 语言 | Stars | 最后更新 |\n`;
    markdown += `|------|------|-------|----------|\n`;
    recentlyActive.forEach((star) => {
      const lastUpdate = new Date(star.pushedAt).toLocaleDateString("zh-CN");
      markdown += `| [${star.name}](${star.htmlUrl}) | ${star.language || "N/A"} | ⭐ ${star.stargazersCount.toLocaleString()} | ${lastUpdate} |\n`;
    });
    markdown += `\n`;
  }

  // 高 Star 项目
  const topStarred = stars.sort((a, b) => b.stargazersCount - a.stargazersCount).slice(0, 10);

  if (topStarred.length > 0) {
    markdown += `## ⭐ 最受欢迎项目 (Top 10)\n\n`;
    markdown += `| 排名 | 项目 | 语言 | Stars | Forks |\n`;
    markdown += `|------|------|------|-------|-------|\n`;
    topStarred.forEach((star, index) => {
      markdown += `| ${index + 1} | [${star.name}](${star.htmlUrl}) | ${star.language || "N/A"} | ⭐ ${star.stargazersCount.toLocaleString()} | 🔀 ${star.forksCount.toLocaleString()} |\n`;
    });
    markdown += `\n`;
  }

  markdown += `---\n\n`;
  markdown += `*报告由 StarKeeper 自动生成*\n`;

  return markdown;
}

/**
 * 导出统计报告为 JSON
 * @param {Object} statsData - 统计数据
 * @returns {string} JSON 字符串
 */
export function exportStatsJSON(statsData) {
  return JSON.stringify(statsData, null, 2);
}

/**
 * 导出统计报告为 CSV
 * @param {Object} statsData - 统计数据
 * @returns {string} CSV 文本
 */
export function exportStatsCSV(statsData) {
  const { basic, health, languages, tags } = statsData;

  let csv = `统计类型,指标,数值,占比\n`;

  // 基础统计
  csv += `基础统计,总 Stars 数,${basic.totalStars ?? 0},100%\n`;
  csv += `基础统计,标签数,${basic.totalTags ?? 0},-\n`;
  csv += `基础统计,有笔记,${basic.withNotes ?? 0},${basic.notesPercentage ?? 0}%\n`;
  csv += `基础统计,有 AI 摘要,${basic.withAISummary ?? 0},${basic.aiSummaryPercentage ?? 0}%\n`;

  // 健康度
  if (health) {
    csv += `\n健康度,平均分,${health.averageScore},-\n`;
    csv += `健康度,已分析,${health.analyzedCount},${health.analyzedPercentage}%\n`;
  }

  // 语言分布
  if (languages && languages.length > 0) {
    csv += `\n`;
    languages.slice(0, 10).forEach((lang) => {
      csv += `语言分布,${lang.language},${lang.count},${lang.percentage}%\n`;
    });
  }

  // 标签统计
  if (tags && tags.length > 0) {
    csv += `\n`;
    tags.slice(0, 10).forEach((tag) => {
      csv += `标签统计,${tag.tag},${tag.count},${tag.percentage}%\n`;
    });
  }

  return csv;
}
