/**
 * 导入/导出服务
 * 支持 Markdown、CSV、JSON 格式
 */

/**
 * 导出为 Markdown 格式（按标签分类）
 * @param {Array} stars - Stars 数据数组
 * @param {Object} metadata - 元数据对象（标签、笔记、摘要等）
 * @returns {string} Markdown 文本
 */
export function exportToMarkdown(stars, metadata) {
  let markdown = `# My GitHub Stars Collection\n\n`;
  markdown += `> 导出时间: ${new Date().toLocaleString('zh-CN')}\n`;
  markdown += `> 项目总数: ${stars.length}\n\n`;
  markdown += `---\n\n`;

  // 按标签分组
  const tagGroups = {};
  const untagged = [];

  stars.forEach(star => {
    const repoMeta = metadata[star.id] || {};
    const tags = repoMeta.tags || [];

    if (tags.length === 0) {
      untagged.push(star);
    } else {
      tags.forEach(tag => {
        if (!tagGroups[tag]) {
          tagGroups[tag] = [];
        }
        tagGroups[tag].push(star);
      });
    }
  });

  // 输出有标签的项目
  const sortedTags = Object.keys(tagGroups).sort();
  
  sortedTags.forEach(tag => {
    markdown += `## 🏷️ ${tag}\n\n`;
    
    tagGroups[tag].forEach(star => {
      const repoMeta = metadata[star.id] || {};
      markdown += `### [${star.name}](${star.htmlUrl})\n\n`;
      markdown += `**Owner:** [@${star.owner.login}](${star.owner.htmlUrl})\n\n`;
      
      if (star.description) {
        markdown += `**描述:** ${star.description}\n\n`;
      }
      
      // AI 摘要
      if (repoMeta.aiSummary?.summary) {
        markdown += `**AI 摘要:** ${repoMeta.aiSummary.summary}\n\n`;
        
        if (repoMeta.aiSummary.features?.length > 0) {
          markdown += `**主要功能:**\n`;
          repoMeta.aiSummary.features.forEach(feature => {
            markdown += `- ${feature}\n`;
          });
          markdown += `\n`;
        }
      }
      
      // 笔记
      if (repoMeta.notes) {
        markdown += `**笔记:**\n${repoMeta.notes}\n\n`;
      }
      
      // 统计信息
      markdown += `**统计:** ⭐ ${star.stargazersCount.toLocaleString()} | 🔀 ${star.forksCount.toLocaleString()}`;
      
      if (star.language) {
        markdown += ` | 💻 ${star.language}`;
      }
      
      markdown += `\n\n`;
      markdown += `**更新于:** ${new Date(star.updatedAt).toLocaleDateString('zh-CN')}\n\n`;
      markdown += `---\n\n`;
    });
  });

  // 输出未分类的项目
  if (untagged.length > 0) {
    markdown += `## 📦 未分类\n\n`;
    
    untagged.forEach(star => {
      const repoMeta = metadata[star.id] || {};
      markdown += `### [${star.name}](${star.htmlUrl})\n\n`;
      markdown += `**Owner:** [@${star.owner.login}](${star.owner.htmlUrl})\n\n`;
      
      if (star.description) {
        markdown += `**描述:** ${star.description}\n\n`;
      }
      
      if (repoMeta.aiSummary?.summary) {
        markdown += `**AI 摘要:** ${repoMeta.aiSummary.summary}\n\n`;
      }
      
      markdown += `**统计:** ⭐ ${star.stargazersCount.toLocaleString()} | 🔀 ${star.forksCount.toLocaleString()}`;
      
      if (star.language) {
        markdown += ` | 💻 ${star.language}`;
      }
      
      markdown += `\n\n`;
      markdown += `---\n\n`;
    });
  }

  markdown += `\n---\n\n`;
  markdown += `📅 Generated by [StarKeeper](https://github.com/Naloam/StarKeeper) on ${new Date().toLocaleDateString('zh-CN')}\n`;

  return markdown;
}

/**
 * 导出为 CSV 格式
 * @param {Array} stars - Stars 数据数组
 * @param {Object} metadata - 元数据对象
 * @returns {string} CSV 文本
 */
export function exportToCSV(stars, metadata) {
  // CSV 头部
  let csv = 'Name,Full Name,Owner,Description,URL,Language,Stars,Forks,Updated,Tags,Notes,AI Summary\n';

  stars.forEach(star => {
    const repoMeta = metadata[star.id] || {};
    const tags = (repoMeta.tags || []).join('; ');
    const notes = (repoMeta.notes || '').replace(/"/g, '""').replace(/\n/g, ' ');
    const aiSummary = (repoMeta.aiSummary?.summary || '').replace(/"/g, '""');
    const description = (star.description || '').replace(/"/g, '""');

    csv += `"${star.name}",`;
    csv += `"${star.fullName}",`;
    csv += `"${star.owner.login}",`;
    csv += `"${description}",`;
    csv += `"${star.htmlUrl}",`;
    csv += `"${star.language || ''}",`;
    csv += `${star.stargazersCount},`;
    csv += `${star.forksCount},`;
    csv += `"${new Date(star.updatedAt).toISOString()}",`;
    csv += `"${tags}",`;
    csv += `"${notes}",`;
    csv += `"${aiSummary}"\n`;
  });

  return csv;
}

/**
 * 导出为 JSON 格式（完整数据）
 * @param {Array} stars - Stars 数据数组
 * @param {Object} metadata - 元数据对象
 * @returns {string} JSON 文本
 */
export function exportToJSON(stars, metadata) {
  const exportData = {
    version: '1.0.0',
    exportedAt: new Date().toISOString(),
    totalCount: stars.length,
    repositories: stars.map(star => {
      const repoMeta = metadata[star.id] || {};
      
      return {
        id: star.id,
        name: star.name,
        fullName: star.fullName,
        owner: {
          login: star.owner.login,
          avatar: star.owner.avatarUrl,
          url: star.owner.htmlUrl,
        },
        description: star.description,
        url: star.htmlUrl,
        homepage: star.homepage,
        language: star.language,
        stars: star.stargazersCount,
        forks: star.forksCount,
        watchers: star.watchersCount,
        openIssues: star.openIssuesCount,
        createdAt: star.createdAt,
        updatedAt: star.updatedAt,
        pushedAt: star.pushedAt,
        topics: star.topics || [],
        // 用户元数据
        metadata: {
          tags: repoMeta.tags || [],
          notes: repoMeta.notes || '',
          color: repoMeta.color || '#3B82F6',
          aiSummary: repoMeta.aiSummary || null,
        },
      };
    }),
  };

  return JSON.stringify(exportData, null, 2);
}

/**
 * 触发文件下载
 * @param {string} content - 文件内容
 * @param {string} filename - 文件名
 * @param {string} mimeType - MIME 类型
 */
export function downloadFile(content, filename, mimeType = 'text/plain') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * 导出为 Markdown 并下载
 */
export function exportAndDownloadMarkdown(stars, metadata) {
  const markdown = exportToMarkdown(stars, metadata);
  const filename = `github-stars-${new Date().toISOString().split('T')[0]}.md`;
  downloadFile(markdown, filename, 'text/markdown');
}

/**
 * 导出为 CSV 并下载
 */
export function exportAndDownloadCSV(stars, metadata) {
  const csv = exportToCSV(stars, metadata);
  const filename = `github-stars-${new Date().toISOString().split('T')[0]}.csv`;
  downloadFile(csv, filename, 'text/csv');
}

/**
 * 导出为 JSON 并下载
 */
export function exportAndDownloadJSON(stars, metadata) {
  const json = exportToJSON(stars, metadata);
  const filename = `github-stars-${new Date().toISOString().split('T')[0]}.json`;
  downloadFile(json, filename, 'application/json');
}

/**
 * 获取导出统计信息
 */
export function getExportStats(stars, metadata) {
  const taggedCount = stars.filter(star => {
    const repoMeta = metadata[star.id] || {};
    return (repoMeta.tags || []).length > 0;
  }).length;

  const withNotesCount = stars.filter(star => {
    const repoMeta = metadata[star.id] || {};
    return repoMeta.notes && repoMeta.notes.trim().length > 0;
  }).length;

  const withAISummaryCount = stars.filter(star => {
    const repoMeta = metadata[star.id] || {};
    return repoMeta.aiSummary && repoMeta.aiSummary.summary;
  }).length;

  const allTags = new Set();
  stars.forEach(star => {
    const repoMeta = metadata[star.id] || {};
    (repoMeta.tags || []).forEach(tag => allTags.add(tag));
  });

  return {
    total: stars.length,
    tagged: taggedCount,
    untagged: stars.length - taggedCount,
    withNotes: withNotesCount,
    withAISummary: withAISummaryCount,
    totalTags: allTags.size,
  };
}
